In [78]:
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time
from geopy.exc import GeocoderTimedOut
from geopy.geocoders import Nominatim
url ='https://www.zomato.com/bangalore/'
driver = webdriver.Firefox()
driver.get(url)

In [79]:
soup = BeautifulSoup(driver.page_source,"html.parser")

In [106]:
list = []
for i in soup.find_all('h5'):
   list.append(str(i))

location_name=[]
for i in list:
    try:
        if  ('sc-1uh2q3e-0 sc-dREXXX bHXBca')  in i:
            location_name.append(i)
    except:
        pass
for i in list:
    try:
        if  ('sc-1uh2q3e-0 sc-kXeGPI eyWgms')  in i:
            location_name.append(i)
    except:
        pass
location_name

['<h5 class="sc-1uh2q3e-0 sc-dREXXX bHXBca">Indiranagar</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-dREXXX bHXBca">Marathahalli</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-dREXXX bHXBca">Whitefield</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-dREXXX bHXBca">Koramangala 5th Block</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-dREXXX bHXBca">HSR</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-dREXXX bHXBca">Jayanagar</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-dREXXX bHXBca">JP Nagar</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-dREXXX bHXBca">Sarjapur Road</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Lavelle Road</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Malleshwaram</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">BTM</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">MG Road</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Koramangala 4th Block</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Kalyan Nagar</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Electronic City</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Bannerghatta Road</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Bellandur</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Koramangala 7th Block</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">New BEL Road</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Residency Road</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Koramangala 6th Block</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Church Street</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Brigade Road</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Old Airport Road</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Banashankari</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Basavanagudi</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Rajajinagar</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Brookefield</h5>',
 '<h5 class="sc-1uh2q3e-0 sc-kXeGPI eyWgms">Kammanahalli</h5>']

In [113]:
loc = soup.find_all('h5',{'class':'sc-1uh2q3e-0 sc-dREXXX bHXBca'})
loc1 = soup.find_all('h5',{'class':'sc-1uh2q3e-0 sc-kXeGPI eyWgms'})
location = []
for i in loc:
    location.append(i.text)
for i in loc1:
    location.append(i.text)
len(location)

29

In [108]:
list = []
for i in soup.find_all('p'):
   list.append(str(i))

no_of_restaurant=[]
for i in list:
    try:
        if  ('places')  in i:
            no_of_restaurant.append(i)
    except:
        pass
no_of_restaurant

['<p class="sc-1hez2tp-0 bBZBLJ">439 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">718 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">799 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">188 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">607 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">428 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">476 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">487 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">68 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">297 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">777 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">68 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">62 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">313 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">769 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">476 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">299 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">154 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">344 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">55 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">109 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">61 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">97 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">97 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">346 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">246 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">395 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">229 places</p>',
 '<p class="sc-1hez2tp-0 bBZBLJ">219 places</p>']

In [114]:
from itertools import count


counts = soup.find_all('p',{'class':'sc-1hez2tp-0 bBZBLJ'})
count_of_restaurant = []
for i in counts:
    count_of_restaurant.append(i.text)
len(count_of_restaurant)

29

In [115]:

col=['location', 'count_of_restaurant']
df=pd.DataFrame({'location':location, 'count_of_restaurant' :count_of_restaurant})
df

                 location count_of_restaurant
0             Indiranagar          439 places
1            Marathahalli          718 places
2              Whitefield          799 places
3   Koramangala 5th Block          188 places
4                     HSR          607 places
5               Jayanagar          428 places
6                JP Nagar          476 places
7           Sarjapur Road          487 places
8            Lavelle Road           68 places
9            Malleshwaram          297 places
10                    BTM          777 places
11                MG Road           68 places
12  Koramangala 4th Block           62 places
13           Kalyan Nagar          313 places
14        Electronic City          769 places
15      Bannerghatta Road          476 places
16              Bellandur          299 places
17  Koramangala 7th Block          154 places
18           New BEL Road          344 places
19         Residency Road           55 places
20  Koramangala 6th Block          109 places
21          Church Street           61 places
22           Brigade Road           97 places
23       Old Airport Road           97 places
24           Banashankari          346 places
25           Basavanagudi          246 places
26            Rajajinagar          395 places
27            Brookefield          229 places
28           Kammanahalli          219 places